export const JOBAPPLICATION_LOAD_REQUEST = "JOBAPPLICATION_LOAD_REQUEST";
export const JOBAPPLICATION_LOAD_SUCCESS = "JOBAPPLICATION_LOAD_SUCCESS";
export const JOBAPPLICATION_LOAD_FAIL = "JOBAPPLICATION_LOAD_FAIL";
export const JOBAPPLICATION_LOAD_RESET = "JOBAPPLICATION_LOAD_RESET";

export const JOBAPPLICATION_LOAD_SINGLE_REQUEST = "JOBAPPLICATION_LOAD_SINGLE_REQUEST";
export const JOBAPPLICATION_LOAD_SINGLE_SUCCESS = "JOBAPPLICATION_LOAD_SINGLE_SUCCESS";
export const JOBAPPLICATION_LOAD_SINGLE_FAIL = "JOBAPPLICATION_LOAD_SINGLE_FAIL";
export const JOBAPPLICATION_LOAD_SINGLE_RESET = "JOBAPPLICATION_LOAD_SINGLE_RESET";

export const REGISTER_JOBAPPLICATION_REQUEST = "REGISTER_JOBAPPLICATION_REQUEST";
export const REGISTER_JOBAPPLICATION_SUCCESS = "REGISTER_JOBAPPLICATION_SUCCESS";
export const REGISTER_JOBAPPLICATION_FAIL = "REGISTER_JOBAPPLICATION_FAIL";
export const REGISTER_JOBAPPLICATION_RESET = "REGISTER_JOBAPPLICATION_RESET";

export const UPDATE_JOBAPPLICATION_REQUEST = "UPDATE_JOBAPPLICATION_REQUEST";
export const UPDATE_JOBAPPLICATION_SUCCESS = "UPDATE_JOBAPPLICATION_SUCCESS";
export const UPDATE_JOBAPPLICATION_FAIL = "UPDATE_JOBAPPLICATION_FAIL";
export const UPDATE_JOBAPPLICATION_RESET = "UPDATE_JOBAPPLICATION_RESET";

export const DELETE_JOBAPPLICATION_REQUEST = "DELETE_JOBAPPLICATION_REQUEST";
export const DELETE_JOBAPPLICATION_SUCCESS = "DELETE_JOBAPPLICATION_SUCCESS";
export const DELETE_JOBAPPLICATION_FAIL = "DELETE_JOBAPPLICATION_FAIL";
export const DELETE_JOBAPPLICATION_RESET = "DELETE_JOBAPPLICATION_RESET";
