export const TASK_LOAD_REQUEST = "TASK_LOAD_REQUEST";
export const TASK_LOAD_SUCCESS = "TASK_LOAD_SUCCESS";
export const TASK_LOAD_FAIL = "TASK_LOAD_FAIL";
export const TASK_LOAD_RESET = "TASK_LOAD_RESET";

export const TASK_LOAD_SINGLE_REQUEST = "TASK_LOAD_SINGLE_REQUEST";
export const TASK_LOAD_SINGLE_SUCCESS = "TASK_LOAD_SINGLE_SUCCESS";
export const TASK_LOAD_SINGLE_FAIL = "TASK_LOAD_SINGLE_FAIL";
export const TASK_LOAD_SINGLE_RESET = "TASK_LOAD_SINGLE_RESET";

export const REGISTER_TASK_REQUEST = "REGISTER_TASK_REQUEST";
export const REGISTER_TASK_SUCCESS = "REGISTER_TASK_SUCCESS";
export const REGISTER_TASK_FAIL = "REGISTER_TASK_FAIL";
export const REGISTER_TASK_RESET = "REGISTER_TASK_RESET";

