export const TASKALLOTMENT_LOAD_REQUEST = "TASKALLOTMENT_LOAD_REQUEST";
export const TASKALLOTMENT_LOAD_SUCCESS = "TASKALLOTMENT_LOAD_SUCCESS";
export const TASKALLOTMENT_LOAD_FAIL = "TASKALLOTMENT_LOAD_FAIL";
export const TASKALLOTMENT_LOAD_RESET = "TASKALLOTMENT_LOAD_RESET";

export const TASKALLOTMENT_LOAD_SINGLE_REQUEST =
  "TASKALLOTMENT_LOAD_SINGLE_REQUEST";
export const TASKALLOTMENT_LOAD_SINGLE_SUCCESS =
  "TASKALLOTMENT_LOAD_SINGLE_SUCCESS";
export const TASKALLOTMENT_LOAD_SINGLE_FAIL = "TASKALLOTMENT_LOAD_SINGLE_FAIL";
export const TASKALLOTMENT_LOAD_SINGLE_RESET =
  "TASKALLOTMENT_LOAD_SINGLE_RESET";

export const REGISTER_TASKALLOTMENT_REQUEST = "REGISTER_TASKALLOTMENT_REQUEST";
export const REGISTER_TASKALLOTMENT_SUCCESS = "REGISTER_TASKALLOTMENT_SUCCESS";
export const REGISTER_TASKALLOTMENT_FAIL = "REGISTER_TASKALLOTMENT_FAIL";
export const REGISTER_TASKALLOTMENT_RESET = "REGISTER_TASKALLOTMENT_RESET";
